### ISSUE TITLE
Gives error: Wrong number of arguments: (1 . 1), 2

### ISSUE THREAD

**Issue by borgauf** [ljos/ob-prolog#10]
On my original system, as well on a built-from-scratch system, babel prolog won't work for me. I've got latest swi-prolog 7.4.0 installed, along with Emacs 25.1.1, and org 9.0.4, along with ob-prolog 20170102.953, and prolog (major mode) 1.22. Anything I put in a code block, e.g., 

> #+BEGIN_SRC prolog
> [likes.pl].
> #+END_SRC

results in (from \*Messages\*)

> executing Prolog code block...
> executing Prolog source code block
> org-babel-variable-assignments:prolog: Wrong number of arguments: (1 . 1), 2

Doing C-h f brings up 

> org-babel-variable-assignments:prolog is a compiled Lisp function in
> ‘ob-prolog.el’.
> (org-babel-variable-assignments:prolog PARAMS)
> Not documented.

. . . and I found it here in ob-prolog.el, but can't fathom what is going wrong.

Regular, non-org prolog major mode interactions work fine.

**Comment by ljos** [comment]
Hi - thank you for reporting. I had accidentally left one of the parameters of `org-babel-get-header` when I replaced it as it has gotten removed from org-mode. The new function `org-babel--get-vars` only takes one argument.
