### ISSUE TITLE
Evaluation of code block does nothing

### ISSUE THREAD

**Issue by borgauf** [ljos/ob-prolog#11]
Here's my test code using latest ob-prolog (following : [(http://www.cpp.edu/~jrfisher/www/prolog_tutorial/contents.html)](url) )
> #+BEGIN_SRC prolog 
> ['2_2.pl']
> #+END_SRC

where 2_2.pl is

> factorial(0,1). 
> factorial(N,F) :-  
>    N>0, 
>    N1 is N-1, 
>    factorial(N1,F1), 
>    F is N * F1.
> /*------------------------------*/
> factorial(0,F,F). 
> factorial(N,A,F) :-  
>     N > 0, 
>     A1 is N*A, 
>     N1 is N -1, 
>     factorial(N1,A1,F). 
> 
Doing C-c C-c gives no output, saying (from \*Messages\*)

> executing Prolog code block...
> executing Prolog source code block
> Wrote /tmp/babel-96244bw/ob-input-96248t0
> Error reading results: (beginning-of-buffer)
> Code block produced no output.

Then I try this:

> #+BEGIN_SRC prolog 
> factorial(10,What).
> #+END_SRC

. . . and get the same response. I try the raw code in 2_2.pl in a code block, again, same response. Please advise. (BTW, thank you very much for your prompt answer to my last question.)

**Comment by ljos** [comment]
When running as a script prolog doesn't do any output unless you print it to the screen yourself with e.g. `write` or `format`. If run in a session you will see the output that you are looking for. I think the error is from org-babel trying to read the results and not finding anything. I will look into it.

**Comment by ljos** [comment]
The error should now not show anymore.

**Comment by borgauf** [comment]
Got your update. I'm still not getting any output after loading the factorial code above with

> #+BEGIN_SRC prolog 
> factorial(10,What).
> #+END_SRC
> 

I'm used to org-mode babel giving me output on a code block like this. Also, no Prolog REPL is started. \*Messages\* says it's writing to /tmp/babel..., but it's only echoing the command. How can I get the "usual" babel behavior?

**Comment by borgauf** [comment]
Not sure if related, but elpa's prolog mode 1.22 (from marmalade) has a bug that I've reported [https://github.com/usergenic/emacs.d/issues/1](url).

**Comment by ljos** [comment]
Sorry I've been a bit slow on this, but I think that it is doing what it is supposed to be doing. If don't print anything, what do you expect a program to return? If you run the program in a session you can get the output that I think you are after, but running a program that has no output shouldn't give any output either.
