### ISSUE TITLE
create_prolog_flag/3 error upon using ob-prolog

### ISSUE THREAD

**Issue by wouterbeek** [ljos/ob-prolog#12]
For some reason I cannot get a simple Prolog snippet to work in ob-prolog:

```org
#+BEGIN_SRC prolog :goal a(X)
a(a).
#+END_SRC
```
`C-c C-c` gives the following error:

```
ERROR: Prolog initialisation failed:
ERROR: create_prolog_flag/3: Arguments are not sufficiently instantiated
```

I'm a bit surprised to see this error, ob-prolog does not seem to set a SWI-Prolog flag from its code?

My Prolog-related configuration is as follows:

```
(org-babel-do-load-languages
 'org-babel-load-languages
 '(...
   (prolog . t)))
(autoload 'run-prolog "prolog" "Start a Prolog sub-process." t)
(autoload 'prolog-mode "prolog" "Major mode for editing Prolog programs." t)
(setq prolog-system 'swi)
(add-to-list 'auto-mode-alist '("\\.pl$" . prolog-mode))
(setq prolog-indent-width 2)
```

**Comment by ljos** [comment]
Do you have something strange in your `.swiplrc` file? It seems to work fine on my machine. There is perhaps something wrong with the session handling -- right now it seemed it didn't complete properly -- but you are not using that feature here.

**Comment by wouterbeek** [comment]
I've renamed the initialization file to `.swiplrc.old` for testing purposes, but I still get the same error.  I can show this to Jan Wielemaker when I see him.

**Comment by ljos** [comment]
I figured it out. The loaded files are not available when running the goal as -t, but it is when running as -g. We therefore load the files, run the goal, and then we run halt. No more insufficiently instantiated variables.
