### ISSUE TITLE
Code block produced no output

### ISSUE THREAD

**Issue by dirko** [ljos/ob-prolog#18]
Hi! Thanks for this package, it will really help if I can get it to work.

When I add a block like
``` org
#+begin_src prolog goal: a(X).
a(pizza).
#+end_src
``` 

and execute it I just get `Code block produced no output`. Am I maybe missing something obvious, or how can I debug this? It is not entirely clear to me how to specify the goal.

**Comment by ljos** [comment]
If you run this as a program it doesn't actually print anything. You will have to run it as a session to get the output that you expect. This is the same if you run a prolog script on the command line or any program. If it doesn't actually write anything to the output, it won't display anything.

**Comment by dirko** [comment]
Ah thanks - I've only started learning prolog so I'm just familiar with the interactive interface. 
It seems what I wanted was something like
```org
#+begin_src prolog 
a(pizza).
:- initialization((a(X), writeln(X))).
#+end_src

#+RESULTS:
: pizza
```
